ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/ec2-user/workspace/cf_rank/main.py", line 230, in <module>
    main(args)
  File "/home/ec2-user/workspace/cf_rank/main.py", line 184, in main
    trainer = local_trainer(train_loader=train_dataloader,val_loader=test_dataloader,
  File "/home/ec2-user/workspace/cf_rank/engine.py", line 64, in __init__
    self.resume(load_path=args.load_path_ranker, model='arranger')
AttributeError: 'Namespace' object has no attribute 'load_path_ranker'
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/ec2-user/workspace/cf_rank/main.py", line 232, in <module>
    main(args)
  File "/home/ec2-user/workspace/cf_rank/main.py", line 186, in main
    trainer = local_trainer(train_loader=train_dataloader,val_loader=test_dataloader,
  File "/home/ec2-user/workspace/cf_rank/engine.py", line 64, in __init__
    self.resume(load_path=args.load_path_ranker, model='arranger')
  File "/home/ec2-user/workspace/cf_rank/engine.py", line 394, in resume
    checkpoint = torch.load(load_path, map_location='cpu')
  File "/home/ec2-user/anaconda3/envs/rank3/lib/python3.9/site-packages/torch/serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ec2-user/anaconda3/envs/rank3/lib/python3.9/site-packages/torch/serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ec2-user/anaconda3/envs/rank3/lib/python3.9/site-packages/torch/serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/workspace/outputs/ranker_org_2e-5_log_concat/checkpoints/checkpoint30.pth'
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/ec2-user/workspace/cf_rank/main.py", line 232, in <module>
    main(args)
  File "/home/ec2-user/workspace/cf_rank/main.py", line 186, in main
    trainer = local_trainer(train_loader=train_dataloader,val_loader=test_dataloader,
  File "/home/ec2-user/workspace/cf_rank/engine.py", line 64, in __init__
    self.resume(load_path=args.load_path_ranker, model='arranger')
  File "/home/ec2-user/workspace/cf_rank/engine.py", line 394, in resume
    checkpoint = torch.load(load_path, map_location='cpu')
  File "/home/ec2-user/anaconda3/envs/rank3/lib/python3.9/site-packages/torch/serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ec2-user/anaconda3/envs/rank3/lib/python3.9/site-packages/torch/serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ec2-user/anaconda3/envs/rank3/lib/python3.9/site-packages/torch/serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/workspace/outputs/ranker_org_2e-5_log_concat/checkpoints/checkpoint20.pth'
ERROR:root:An error occurred:
Traceback (most recent call last):
  File "/home/ec2-user/workspace/cf_rank/main.py", line 232, in <module>
    main(args)
  File "/home/ec2-user/workspace/cf_rank/main.py", line 186, in main
    trainer = local_trainer(train_loader=train_dataloader,val_loader=test_dataloader,
  File "/home/ec2-user/workspace/cf_rank/engine.py", line 64, in __init__
    self.resume(load_path=args.load_path_ranker, model='arranger')
  File "/home/ec2-user/workspace/cf_rank/engine.py", line 394, in resume
    checkpoint = torch.load(load_path, map_location='cpu')
  File "/home/ec2-user/anaconda3/envs/rank3/lib/python3.9/site-packages/torch/serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ec2-user/anaconda3/envs/rank3/lib/python3.9/site-packages/torch/serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ec2-user/anaconda3/envs/rank3/lib/python3.9/site-packages/torch/serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/workspace/outputs/ranker_org_2e-5_log_noconcat/checkpoints/checkpoint20.pth'
